### ISSUE TITLE
After uninstalling, I cannot queue in tf2 anymore

### ISSUE THREAD

**Issue by sauceroll** [BeepIsla/valve-region-selector#29]
Hi, I've uninstalled this program multiple times following the instructions on the README page and when I boot tf2 and check my matchmaking settings not only do no official valve servers display, but I am unable to queue matches in a party and it consistently fails and attempts to retry to no avail. I've tried flushing my dns cache, reinstalling tf2, verifying integrity of game files and so on and so far nothing has fixed this. I am unsure if this is an issue with the program itself but I have no clue what to do anymore. Thanks again. 
![hl2_2021-10-19_21-15-35](https://user-images.githubusercontent.com/68386441/137981169-9ad26690-1062-47e0-9be2-a47b25498c2d.png)

**Comment by BeepIsla** [comment]
This is not related to the program.

When you install it it doesn't do anything yet, when you click enable it sets Steam up to send all data through the program instead of directly to Steam servers. Using this the program modifies the "ping packet" which tells TF2 which servers you have a low ping to. So when you disable/uninstall the program Steam will simply connect to a regular Steam server and no packets will be modified. So I don't think this is an issue with the program.

As far as I know having an empty ping-list is a bug but doesn't actually stop you from finding a game, at least it didn't a few years ago when I had such an issue.

I assume you mean the queue just stops on its own? I had a similar issue a few weeks ago with a friend and we just decided to not play the game after a few minutes of trying. The next time we played (A few days later) it all worked fine again.

If you mean that you can queue but just not find any game even after a long queue time it could have many reasons such as selected maps, time of day, or simply broken servers as that happened in the past once if I remember correctly.

Other than that I don't know what could fix it. As far as I know NA servers had some issues a few days ago, maybe that is related? I don't know.

Just to make sure this is not a program issue I will do some tests with it but as I explained at the beginning I highly doubt it is.

**Comment by sauceroll** [comment]
Thanks again - I find that I was able to join a server on my own but whenever I queued with a friend to try connect to e.g. European servers, it would fail to connect and be in a retry loop. So I have been pretty much unable to queue in a party to join servers as a group but I can join on my own

**Comment by BeepIsla** [comment]
> it would fail to connect and be in a retry loop

I assume similar to what is being described [in these Reddit posts?](https://www.reddit.com/r/tf2/search/?q=connect&include_over_18=on&restrict_sr=on&t=all&sort=new) It just seems to be a thing that is happening and nobody knows why.

**Comment by sauceroll** [comment]
Yep, just like that - then I guess its valve again.......  thanks again for assisting
